apiVersion: v2
name: sortie
description: A Helm chart for Sortie - application launcher with Kubernetes pod orchestration
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - sortie
  - application-launcher
  - vnc
  - kubernetes
home: https://github.com/rjsadow/sortie
maintainers:
  - name: rjsadow
