apiVersion: v2
name: launchpad
description: A Helm chart for Launchpad - application launcher with Kubernetes pod orchestration
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - launchpad
  - application-launcher
  - vnc
  - kubernetes
home: https://github.com/rjsadow/launchpad
maintainers:
  - name: rjsadow
