---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sortie.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sortie.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
