---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "launchpad.fullname" . }}-session-manager
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "launchpad.fullname" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "launchpad.fullname" . }}-session-manager
  apiGroup: rbac.authorization.k8s.io
