---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "launchpad.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
